name: Release

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Getting version
      run: |
        version=$(cat gradle.properties | grep -Po "(?<=version=)\d+\.\d+\.\d+")
        echo "The version is $version"
